apiVersion: v1
kind: Pod
metadata:
  name: debian-debug
  labels:
    app: debian-debug
spec:
  containers:
    - name: debian
      image: debian:bullseye
      command: [ "/bin/bash", "-c", "--" ]
      args:
        - |
          apt update && \
          apt install -y iproute2 iputils-ping dnsutils curl netcat traceroute && \
          tail -f /dev/null
      stdin: true
      tty: true
  restartPolicy: Never