apiVersion: v1
kind: Pod
metadata:
  name: socks-proxy
  labels:
    app: socks-proxy
spec:
  restartPolicy: Never
  containers:
    - name: socks-proxy
      image: serjs/go-socks5-proxy
      ports:
        - containerPort: 1080
      env:
        - name: PROXY_USER
          value: "bruno-tunnel"
        - name: PROXY_PASSWORD
          value: ""